name: rescue_radar
description: "A new Flutter project."
publish_to: 'none' # Prevent publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  web_socket_channel: ^2.4.0
  # Remove camera package for ESP32
  url_launcher: ^6.3.0
  fl_chart: ^0.68.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.1.0
  multicast_dns: ^0.3.0
  window_manager: ^0.3.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  assets:
    - images/cam inter.png
    - images/data logging.png
    - images/heart.png
    - images/map.png